# Generated by Django 4.0.10 on 2023-06-07 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('College_ID', models.AutoField(primary_key=True, serialize=False)),
                ('college_name', models.CharField(max_length=255)),
                ('College_Address', models.CharField(max_length=255)),
                ('college_mobile', models.CharField(max_length=20)),
                ('contact_no', models.CharField(max_length=20)),
                ('college_site', models.URLField()),
                ('person_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Designation_ID', models.IntegerField()),
                ('Designation_Name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('District_ID', models.IntegerField()),
                ('District_Code', models.IntegerField()),
                ('District_Name', models.CharField(max_length=255)),
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Division_ID', models.IntegerField()),
                ('Division_Name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Role_ID', models.IntegerField()),
                ('Role_Name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
                ('session_start_year', models.DateField()),
                ('session_end_year', models.DateField()),
                ('closing_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Town_ID', models.IntegerField()),
                ('Town_Name', models.CharField(max_length=255)),
                ('District_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='District', to='PpcBackEnd.district')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAdmissionForm',
            fields=[
                ('Std_id', models.AutoField(primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('Full_Name', models.CharField(max_length=200)),
                ('Fathers_Name', models.CharField(max_length=100)),
                ('Date_of_Birth', models.DateField()),
                ('Religion', models.CharField(max_length=100)),
                ('Qualification', models.CharField(max_length=200)),
                ('Matric_Image', models.ImageField(upload_to='admsn_images/')),
                ('Student_Image', models.ImageField(upload_to='admsn_images/')),
                ('Student_CNIC_Image', models.ImageField(upload_to='admsn_images/')),
                ('Institution_Admission_Letter', models.ImageField(upload_to='', verbose_name='admsn_images/')),
                ('Permanent_Address', models.CharField(max_length=254)),
                ('Student_email', models.EmailField(max_length=100, null=True)),
                ('Student_mobile', models.CharField(max_length=15, null=True)),
                ('College_Name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PpcBackEnd.college')),
                ('Session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PpcBackEnd.session')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='Division_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PpcBackEnd.division'),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department_ID', models.IntegerField()),
                ('Department_Name', models.CharField(max_length=255)),
                ('Designation_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designation', to='PpcBackEnd.designation')),
            ],
        ),
    ]
